### ISSUE TITLE
速度对比

### ISSUE THREAD

**Issue by Minotaur-CN** [rexbu/libGDL#1]
hi,您好
libGDL目前和ncnn的速度有对比么？

**Comment by rexbu** [comment]
没有做哇，我有给出mnist的速度，再有ncnn计算mnist的速度，就有一个简单的对比了。
libGDL卷积过程都是利用gpu算的，所以对gpu的性能依赖比较大，如果较老的手机速度肯定比ncnn要差，对于较新的机器，我觉得应该速度比ncnn快吧

**Comment by Minotaur-CN** [comment]
cool！
